categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Hot Fixes'
    labels:
      - 'hotfix'
  - title: 'Data Integration'
    label:
      - 'data'
      - 'data-integration'
exclude-labels:
  - 'skip-changelog'
  - 'skip-rn'
  - 'skip-release-note'
  - 'no-release-note'
  - 'no-rn'
  - 'no-changelog'
  - 'new-release'
change-template: '- #$NUMBER - $TITLE'
change-title-escapes: '\<*&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  $CHANGES
